In [1]:
import numpy as np
import copy

In [2]:
%%time
arr1 = []
n = 10**7
for i in range(n):
    arr1.append(i*5)

CPU times: total: 2.69 s
Wall time: 2.74 s


In [3]:
%%time
arr2 = [i for i in range(0, 5*n, 5)]

CPU times: total: 1.14 s
Wall time: 1.11 s


In [4]:
arr1 == arr2

True

In [5]:
%%time
arr3 = np.arange(stop=5*n, step=5)

CPU times: total: 31.2 ms
Wall time: 32.9 ms


In [6]:
arr3.tolist() == arr1

True

# Библиотека Numpy

* `Numpy` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.

* Пакет `Numpy` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В `Numpy` реализовано много операций над массивами в целом.

___
## Одномерный массив

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.arange(start=-5, stop=5, step=0.5)
c = np.linspace(start=0, stop=100, num=51)
d = np.logspace(start=0, stop=10, num=11)

In [8]:
type(a)

numpy.ndarray

In [9]:
print(f'a length: {len(a)}') # количество элементов
print(f'b shape: {b.shape}') # количество элементов по осям
print(f'c dimention: {c.ndim}') # размерность
print(f'd size: {d.size}') # количество элементов

a length: 5
b shape: (20,)
c dimention: 1
d size: 11


`ndarray` можно использовать в циклах. Но при этом теряется главное преимущество `Numpy` -- быстродействие.

Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.

## Операции над одномерными массивами.

*Все арифметические операции производятся поэлементно.*


In [10]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


Один из операндов может быть скаляром, а не массивом.

In [11]:
print(5 * a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [12]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


В Numpy есть элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (ufunc).

In [13]:
type(np.cos)

numpy.ufunc

In [14]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [15]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.48490665, 2.7080502 ,
       2.89037176, 3.04452244, 3.17805383, 3.29583687, 3.40119738,
       3.49650756])

In [16]:
np.log(b)

C:\Users\zeri1\AppData\Local\Temp\ipykernel_13116\4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Логические операции также производятся поэлементно

In [17]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [18]:
np.any(a == 0), np.all(b < 0)

(False, True)

Маски

In [19]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


**Задание:**

1) Создать массив чисел от $-4 \pi$ до $4 \pi$, количество точек - 100.
2) Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива
3) С помощью `np.all` проверить, что все элементы равны единице.

In [20]:
# your code
P = np.linspace(start=-4 * np.pi, stop=4 * np.pi, num=100)
result = np.sin(P) ** 2 + np.cos(P) ** 2
np.allclose(result, np.ones((1,100), dtype='int')[0])

True

___
## Двумерный массив

In [21]:
A = np.zeros((4, 3))

In [22]:
print(len(A))
print(A.shape)
print(A.ndim)
print(A.size)

4
(4, 3)
2
12


In [23]:
B = np.ones((2, 2))
B

array([[1., 1.],
       [1., 1.]])

In [24]:
E = np.eye(5, 5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
D = np.diag([1, -1])
D

array([[ 1,  0],
       [ 0, -1]])

**Задание:**

Создать квадратную матрицу размера 8, 

на главной диагонали арифметическая прогрессия с шагом 3 (начиная с 3),

а на побочной -1, остальные элементы 0.

In [26]:
# your code
-1 * np.eye(8,8)[::-1] + np.diag(range(3, 27, 3))

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  6.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  9.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., 12., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., 15.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0., 18.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0., 21.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0., 24.]])

___
## Вычисления с матрицами

Суммирование

In [27]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 0, -1]
])
A

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 1,  0, -1]])

In [28]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[5 4 3]
[6 6 0]


In [29]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
A + B

array([[2., 3., 4.],
       [4., 3., 2.],
       [2., 1., 0.]])

Умножение

In [31]:
A = 5 * np.ones((5, 5))
b = np.eye(5) + 1
print(A, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [32]:
print(A * b, '\n') # поэлементное умножение
print(A @ b, '\n') # матричное умножение
print(A.dot(b)) 

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


___
# Линейная алгебра

In [33]:
a = np.array([[2, 1], [2, 3]])
a

array([[2, 1],
       [2, 3]])

Определитель

In [34]:
np.linalg.det(a)

4.0

Нахождениия обратной матрицы

In [35]:
np.linalg.inv(a)

array([[ 0.75, -0.25],
       [-0.5 ,  0.5 ]])

In [36]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [37]:
# np.linalg.inv(c)

### Решение СЛУ

$A \cdot x = n$

In [38]:
a = np.array([
    [1, 2],
    [2, 3]
])
n = np.array([5, -10])

x = np.linalg.solve(a, n)

print(x)
print(a.dot(x))

[-35.  20.]
[  5. -10.]


___
# Практика

In [39]:
from typing import List

## Задание 1

**В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета `numpy` и с ним.**


Для генерации матриц используем фукнцию `random` -- она используется для генерации случайных объектов 
функция `sample` создает случайную выборку. 

В качестве аргумента ей передается кортеж `(i,j)`, здесь `i` - число строк, `j` - число столбцов.

In [40]:
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

print(a)
print(b)

[[0.50229274 0.33546239 0.70902544 ... 0.21605297 0.75341955 0.42332295]
 [0.60363135 0.48475776 0.91154287 ... 0.81100289 0.67509817 0.39982486]
 [0.96012407 0.81484264 0.55680899 ... 0.30346583 0.11259069 0.28572525]
 ...
 [0.37747164 0.72305555 0.53247429 ... 0.96550482 0.03874845 0.92655865]
 [0.88219392 0.43814778 0.91692674 ... 0.52865357 0.46488898 0.27777603]
 [0.47789889 0.97500277 0.80412132 ... 0.44291076 0.19117169 0.9703657 ]]
[[0.39628137 0.81220941 0.50902778 ... 0.48968201 0.61643196 0.42998229]
 [0.2891393  0.60784299 0.02842739 ... 0.3572451  0.98699848 0.3430916 ]
 [0.75685969 0.9368772  0.5179022  ... 0.35374777 0.43534768 0.64639782]
 ...
 [0.81365857 0.44167484 0.80081866 ... 0.55723206 0.04440475 0.10652743]
 [0.34202282 0.05293823 0.36335665 ... 0.91955869 0.7484609  0.68309241]
 [0.00300235 0.56833023 0.89671661 ... 0.08248776 0.38132622 0.33367385]]


Выведите размерность (ранг) каждой матрицы с помощью функции `ndim`.

Используйте функцию `shape`, что она вывела?

In [41]:
# your code
a.ndim

2

In [42]:
b.ndim

2

In [43]:
a.shape

(100, 100)

In [44]:
b.shape

(100, 100)

In [45]:
a = np.random.sample((2, 2))
b = np.random.sample((2, 2))

In [46]:
def mult(a: List[List[float]], b: List[List[float]]) -> List[List[float]]:
    """  
    a: list of lists, n x m size, each contains floats --- первая матрица-аргумент
    b: list of lists, m x k size, each contains floats --- вторая матрица-аргумент
    return c: list of lists, n x k size, each contains floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью n x m и m x k
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy.
    """
    time = [ [0]*len(b[0]) for i in range(len(a))]
    for t in range(len(a)):
        for e in range(len(b[0])):
            for m in range(len(b)):
                time[t][e] += a[t][m] * b[m][e]
    return time
ab = mult(a,b)
ab

[[0.6763812688428017, 0.08465434974725064],
 [0.7960908997624238, 0.089220373534407]]

In [47]:
def np_mult(a: np.ndarray[float], b: np.ndarray[float]) -> np.ndarray[float]:
    """  
    a: np.array[n, m] --- первая матрица-аргумент
    b: np.array[m, k] --- вторая матрица-аргумент
    return c: np.array[n, k] --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью n x m и m x k
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy.
    """
    c = np.dot(a,b)
    return c

In [48]:
c

array([[2, 1],
       [6, 3]])

In [49]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a.tolist(), b.tolist())

CPU times: total: 0 ns
Wall time: 0 ns


In [50]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [51]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

## Задание 2

**Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью `numpy` и без. Засеките время работы, как это показано в заданиях выше.**


In [52]:
a = np.random.sample((1, 3))[0]
b = np.random.sample((1, 3))[0]

print(a, b)

[0.99801387 0.65898857 0.37385279] [0.62591079 0.61540409 0.70698624]


In [53]:
def scalar_product(a: List[float], b: List[float]) -> float:
    """  
    a: list of float numbers of length n --- список длиной n
    b: list of float numbers of length n --- список длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n.
    Возвращает число, равное их скалярному произведению a * b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy.
    """ 
    dot = lambda a, b: sum(map(lambda x, y: x * y, a, b))
    return dot(a, b)

In [54]:
scalar_p = scalar_product(a,b)

In [55]:
def np_scalar_product(a: np.ndarray[float], b: np.ndarray[float]) -> float:
    """  
    a: np.array[, n] --- матрица-строка
    b: np.array[, n] --- матрица-строка
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a * b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy.
    """ 
    return np.dot(a,b)

In [56]:
scalar_p_numpy = np_scalar_product(a,b)

In [57]:
scalar_p

1.2945206904110471

In [58]:
scalar_p_numpy

1.2945206904110471

In [59]:
%time scalar_p = scalar_product(a.tolist(), b.tolist())
%time scalar_p_numpy = np_scalar_product(a, b)

# проверим корректность:
assert np.allclose(scalar_p, scalar_p_numpy)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


**Почему методы `numpy` оказываются эффективнее? Что вы можете сказать о скорости вычислений в `numpy`?**

Ваш ответ: $\cdots$ NumPy частично на Питоне и частично сделана на С и С++ где нужна скорость, оптимизация на современных процессорах. Все типы элементов состоят из одного типа, что увеличивает скорость высчитывания. Также экономит место и работает с многомерными массивами.

## Задание 3

На вход дан двумерный массив $X$. 

Напишите функцию, которая для каждой строчки $x=(x_1, x_2, \cdots, x_n)$ массива $X$ 
строит строчку $s=(s_1, s_2, \cdots, s_n)$,

где $s_k = x_1 + x_2 + \cdots + x_n$,
а затем выдаёт массив из построенных строчек. 

Напишите код без использованием библиотеки `numpy`, а после сравните с результатом функции `np.cumsum`. Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [64]:
A = np.array([
    [1, 2, 3, 4, 5],
    [3, 2, 0,-1, 1],
    [0, 0,-1,-2,-3],
    [0, 1,-1, 1,-1]
])

In [65]:
def cumsum(A: List[List[float]]) -> List[List[float]]:
    """  
    A: list of lists, n x m size --- матрица-аргумент
    return S: list of lists, n x m size --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A.

    Реализуйте функцию, не используя пакет numpy.
    """
    matrics = copy.deepcopy(A)
    for row in range(len(matrics)):
        total=0
        for sell in range(1,len(matrics[row])):
            # sums.append(total)
            matrics[row][sell] +=matrics[row][sell-1]
    return matrics


In [66]:
S1 = cumsum(A)

In [67]:
S1

array([[ 1,  3,  6, 10, 15],
       [ 3,  5,  5,  4,  5],
       [ 0,  0, -1, -3, -6],
       [ 0,  1,  0,  1,  0]])

In [63]:
%time S1 = cumsum(A.tolist())
%time S2 = np.cumsum(A, axis=1)

# проверим корректность:
assert np.allclose(np.array(S1), S2)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns
